sudo: required
dist: trusty

language: c

env:
  global:
    - BUILD_DIR="$TRAVIS_BUILD_DIR/build"
    - secure: "Dw0r4cbZoT0QoIlI7XWLdhPQxL62CQzskdw3tUth4eSWJd/0IIvLq/ogaZZbYWGH4lifI4p5NMzEpHJ5yFjWnO/ZcpVTZ26SJEFwfBrPUzeu3MV30poX89EYxWz+dE4xPFKzAAKnemlcVxfTHE+z3vW5klnjg5bRH3+pFKoFVBX6M2ABPXcigkpbd1dnXqQK+36v0yx/SF4Yg607vLLPVfcmcU+ohT52OENVkoeEllOxmGxdVfdskEVQ9O16BbtxNSthYQFplvFn5RrpvknRarby51E+7eMf9sOey2H6MWtZYFKXKiascUz5ZLPIt0mFCW1x2wFC39cxMZNFURg+hHlGKUGV9Bt7B7K/XAwvPhY6X+td4OYPR2B68vywxpPlShiTg8iduYg1H4bdVzt+1qdRHsg2qmyJe5eQBMwW5fEVOffJhfVAiG5ceDWzQJQt5cEKn/2yxt1bX3sC7Hl6lzTQ1X6DuLWi9cCsKqsAB7ht/ZC1m13YGRyjghG9RDsRfM2FPy0w0iOHDAGrNzQVPPDDxxgNi/xpmqPlkvjRSz3Pmj6VeAZ2cG68pls+oKyzcWEhCeSL3uT3ShKBfrpQcFxVFzsdTWzH6XYul/HHrUnYKGtd3K1MW59Dng5WcD5xi8n76/wmlkXUoWmYNjfGsP5wwcz/yLfc/CRDRB3P4jo="
  matrix:
    - compiler: gcc
      env:
        - MPICC=mpicc
#    - compiler: clang
#    - env: 
#      - MPICC=mpiicc
#      - MPIFC=ifort
    - env:
        - MPIFC=pgfortran

addons:
  coverity_scan:
    project:
      name: sclaomir/fti
      description: Fault Tolerance Interface
    notification_email: scan_notifications@example.com
    build_command_prepend: cmake ..
    build_command: make
    branch_pattern: devel

os:
  - linux

cache:
  apt: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - if [[ "$compiler" = "clang" ]] ; then export CC=clang ; fi
  - if [[ "$MPICC" = "mpicc" ]] ; then sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev ; fi
  - if [[ "$MPICC" = "mpiicc" ]] ; then sudo ./install-icc.sh --components icc,mpi,ifort --dest /opt/intel ; fi
  - if [[ "$MPIFC" = "pgfortran" ]] ; then ./install-pgi.sh --mpi --dest /opt/pgi ; fi
  - if [[ "$MPIFC" = "pgfortran" ]] ; then sudo apt-get install -y libibverbs-dev ; fi
  - if [[ "$MPIFC" = "pgfortran" ]] ; then sudo apt-get install -y librdmacm-dev ; fi
  - if [[ "$MPIFC" = "pgfortran" ]] ; then sudo apt-get -y --force-yes install libibcm1 libibverbs1 ibverbs-utils librdmacm1 rdmacm-utils ibsim-utils ibutils libcxgb3-1 libibmad5 libibumad3 libmlx4-1 libmthca1 libnes1 rds-tools infiniband-diags libibcommon1 mstflint opensm libopensm5 perftest srptools ; fi
# - if [[ "$MPIFC" = "pgfortran" ]] ; then deb http://pkg-ofed.alioth.debian.org/apt/ofed ./ ; fi
#  - if [[ "$MPIFC" = "pgfortran" ]] ; then deb-src http://pkg-ofed.alioth.debian.org/apt/ofed ./ ; fi
#  - if [[ "$MPIFC" = "pgfortran" ]] ; then aptitude update ; fi
#  - if [[ "$MPIFC" = "pgfortran" ]] ; then aptitude install ofed ; fi

before_script:
  - if [[ "$MPICC" = "mpiicc" ]] ; then source before-script-icc.sh ; fi
  - if [[ "$MPIFC" = "pgfortran" ]] ; then source ./before-script-pgi.sh ; fi
 # - sudo apt-get install libc6
  - which mpicc
  - cat /etc/ld.so.conf 
  - cat /etc/ld.so.conf.d/libc.conf 
  - mkdir $BUILD_DIR
  - cd $BUILD_DIR
  - cmake ..
  - make all
  - sudo make install
  - cd ..

script:
  - ./test/tests.sh
